### PR TITLE
added: shi-tomashi corner generator

### PR DESCRIPTION
**Pull request by thundersparkf**
Added a Shi-Tomashi corner generator module

Since corner generation is more dynamic in the pixels used, it would offer a better data abstraction. Plus it is also difficult to ascertain the how many corners were computed by any attacker.

Please let me know if there are any issues
Signed-off-by: thundersparkf <devagastya0@gmail.com>

### CODE REVIEW

**Comment by cedricbonhomme** [comment]
This seems to be an excellent contributions ;-) Thank you very much !
I will have a deeper look tomorrow about this Shi-Tomashi corner generator.

**Comment by cedricbonhomme** [comment]
Hi,
I have a small question... Where is the best place to round (or cast to int) the value here:
https://builds.sr.ht/~cedric/job/633518#task-test-103
x and y are not equal. I would like to make the test happy ;-)

**Comment by thundersparkf** [comment]
Hey! Yes

Firstly, this for consistency's sake the min_distance parameters needs to be changed to 10.0
Screenshot 2021-11-24 at 1 07 52 PM

And then also the 
`np.int0` line must be removed
Screenshot 2021-11-24 at 1 08 18 PM

**Comment by cedricbonhomme** [comment]
Perfect, it works. I just had to use ```assert_allclose``` with a custom relative tolerance.

https://github.com/cedricbonhomme/Stegano/blob/master/tests/test_generators.py#L180

I'll create a new release a bit later.

**Pull request merged**
