### PR TITLE
Implemented Ackemann generators CLI interface

### PR DESCRIPTION
**Pull request by AdrienCos**
This PR introduces two main features:

- The `ackermann_naive` generator has been encapsulated (following the example of the `ackermann` generator)

- Both Ackermann generators now can be used from the `stegano-lsb-set` tool

### CODE REVIEW

**Comment by cedricbonhomme** [comment]
Thank you very much. It's a nice solution!
I'll test this more and make a new release.

**Comment by cedricbonhomme** [comment]
closes #24

**Comment by AdrienCos** [comment]
You're welcome! I may have another feature I want to suggest before the new release, if that's OK. I'll create a new PR to introduce it.

**Comment by cedricbonhomme** [comment]
OK, cool. Can't wait to see this.

**Pull request merged**
